name: hellocalicut
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  carousel_slider: ^2.2.1
  carousel_pro: ^1.0.0
  flutter_swiper: ^1.1.6
  webview_flutter: ^0.3.22+1
  url_launcher: ^5.5.1
  flip_card: ^0.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/jaba.png
   - images/delivery.png
   - images/moving-truck.png
   - images/news.png
   - images/doctor.png
   - images/taxi.png
   - images/ticket.png
   - images/train.png
   - images/movie.png
   - images/corona.png
   - images/more.png
   - images/auto.png
   - images/cake.png
   - images/bakery.png
   - images/mobile.png
   - images/supermarket.png
   - images/govt.png
   - images/jewelery.png
   - images/chicken.jpg
   - images/catering.png
   - images/vegitable.png
   - images/travels.png
   - images/textile.jpg
   - images/turf.png
   - images/tyre.png
   - images/tailor.png
   - images/studio.png
   - images/buses.png
   - images/hardware.png
   - images/hotel.png
   - images/background/back1.jpg
   - images/background/back2.png
   - images/background/back3.jpg
   - images/background/back4.png
   - images/icons/coachingcenter.png
   - images/icons/college.png
   - images/icons/privatetuition.png
   - images/icons/school.png
   - images/icons/training.png
   - images/icons/playschool.png

   
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Anton
      fonts:
        - asset: fonts/Anton-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
